config/routes.rb
Rails.application.routes.draw do

  post '/events/:calendar_id', to: 'google_auths#new_event', as: 'new_event', calendar_id: /[^\/]+/
  get '/events/:calendar_id', to: 'google_auths#events', as: 'events', calendar_id: /[^\/]+/
  get '/redirect', to: 'google_auths#redirect', as: 'redirect'
  get '/callback', to: 'google_auths#callback', as: 'callback'
  get '/calendars', to: 'google_auths#calendars', as: 'calendars'
  get 'patients/show'

  get 'patients/edit'

  root 'statics#home'

  devise_for :users
  devise_for :patients

  get '/records/get_doctors', to: 'records#get_doctors'
  get '/records/show_doctor_event', to: 'records#show_doctor_event'
  get '/records/', to: 'records#index'

  resources :records
  resources :patients
end

app/models/patient.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string
#  born                   :date
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  type                   :string
#  manager_id             :integer
#

class Patient < User
  has_one :avatar, as: :imageable

  has_many :records
  has_many :doctors, through: :records
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def show
    @patient = Patient.find(params[:id])
    @records = @patient.records
  end

  def edit;end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/edit.html.erb
<h1>Patients#edit</h1>
<p>Find me in app/views/patients/edit.html.erb</p>

app/views/patients/show.html.erb
<div class="col-sm-4">
<%= image_tag('ava150.jpg', size: '150x150', alt: 'Avatarka') %>
<hr>
<br>
<ul>
  <li><%= current_patient.email %></li>
  <li><%= current_patient.name %></li>
  <li><%= current_patient.born %></li>
  <li><%= link_to 'Изменить данные', patients_edit_path(current_patient), class: 'btn btn-success' %></li>
</ul>
</div>

<div class="col-sm-8">
  <table>
    <tr>
      <th style="width: 10px;">id</th>
      <th style="width: 80px;">when</th>
      <th style="width: 120px;">на когда запись</th>
      <th style="width: 50px;">spec</th>
      <th style="width: 120px;">doctor</th>
      <th style="width: 50px;">Share to GoogleCalendar</th>
    </tr>
    <% @records.each do |record| %>
      <tr>
        <td style="width: 10px;"><%= record.id %> </td>
        <td style="width: 80px;"><%= record.created_at.strftime('%F') %></td>
        <td style="width: 120px;"><%= record.date_start.strftime('%Y-%m-%d %k:%M') %></td>
        <td style="width: 50px;"><%= record.doctor.specialization.title  %></td>
        <td style="width: 120px;"><%= record.doctor.doctor_detail.first_name + ' ' + record.doctor.doctor_detail.last_name %></td>
        <!-- <td style="width: 50px;"><%#= link_to 'add event to GC', new_event_path(session[:calendar_id]), record_id: record.id, method: 'POST' %></td> -->

        <td style="width: 50px;">
          <% unless session[:calendar_id] %>
            <%= link_to 'Login to google for add in calendar', redirect_url %>
          <% else %>
            <%= link_to 'add event to GC', { controller: 'google_auths',
                                             action: 'new_event',
                                             record_id: record.id,
                                             calendar_id: session[:calendar_id] },
                                          method: 'POST' if record.date_start >= Time.now %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>

</div>