config/routes.rb
Rails.application.routes.draw do

  post '/events/:calendar_id', to: 'google_auths#new_event', as: 'new_event', calendar_id: /[^\/]+/
  get '/events/:calendar_id', to: 'google_auths#events', as: 'events', calendar_id: /[^\/]+/
  get '/redirect', to: 'google_auths#redirect', as: 'redirect'
  get '/callback', to: 'google_auths#callback', as: 'callback'
  get '/calendars', to: 'google_auths#calendars', as: 'calendars'
  get 'patients/show'

  get 'patients/edit'

  root 'statics#home'

  devise_for :users
  devise_for :patients

  get '/records/get_doctors', to: 'records#get_doctors'
  get '/records/show_doctor_event', to: 'records#show_doctor_event'
  get '/records/', to: 'records#index'

  resources :records
  resources :patients
end

app/views/layouts/_footer.html.erb
<footer class=" footer container-fluid text-center">
  <p>Footer Text</p>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Поликлиника', root_path %></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Projects</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if patient_signed_in? %>
          <li><%= link_to 'Мой кабинет', patient_path(current_patient) %></li>
          <li>
            <!-- <span class="glyphicon glyphicon-log-out"></span> -->
            <%= link_to 'Logout', destroy_user_session_path,
                                  class: "glyphicon glyphicon-log-out",
                                  method: 'DELETE' %>
          </li>

        <% else %>
          <li><%= link_to ' Login ', new_patient_session_path, class: "glyphicon glyphicon-log-in" %></li> OR
          <li><%= link_to ' SignUP ', new_patient_registration_path, class: "glyphicon glyphicon-flash" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_leftpanel.html.erb
<p><a href="#">О клинике</a></p>
<p><a href="#">Врачи</a></p>
<p><%= link_to 'Записаться', records_path %></p>
<p><a href="#">Добраться</a></p>
<p><a href="#">Отзывы</a></p>

app/views/layouts/_right_panel.html.erb
<%= render @doctors %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hospital</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/header' %>

    <div class="container-fluid text-center">
    <div class="row content">
      <div class="col-sm-2 sidenav">

        <%= render 'layouts/leftpanel' %>

      </div>
    <div class="col-sm-10 text-left">
      <% if flash.any? %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>

  </div>
</div>


    <%= render 'layouts/footer' %>
  </body>
</html>


<body>







</body>
</html>